version: '3.8'

services:
  dashboard:
    build: .
    ports:
      - "8051:8051"
    environment:
      - HOST=0.0.0.0
      - PORT=8051
      - DASH_DEBUG_MODE=False
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8051"]
      interval: 30s
      timeout: 10s
      retries: 3
